import '@/styles/globals.css'
import NavBar from '@/components/NavBar'
import { auth } from '@/utils/firebase';
import { useAuthState } from 'react-firebase-hooks/auth';
import Login from '../components/Login'
import Head from 'next/head';

export default function App({ Component, pageProps }) {
  const [user] = useAuthState(auth);
  if(!user) return <Login />
  return (
    <>
     <Head >
        <title>BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<NavBar />
    <Component {...pageProps} />
    </>
    )
}
